#!/bin/sh
seed=`head -c 2 /dev/urandom | hexdump -e '"%u"'`
var_actions=`ls -x actions/*.lp`
var_states=`ls -x states/*.lp`
sys_world="world.lp params.lp"
sys_actions="activity.lp $var_actions"
sys_states="states.lp $var_states"
sys_effects="effects.lp results.lp"
sys_conditions="preconditions.lp"
sys_motives="motivation.lp"
sys_english="english.lp disp.lp"
core="$sys_world $sys_actions $sys_states $sys_effects $sys_conditions"
sources="$core $sys_motives constraints.lp $sys_english"
opts="--clasp --rand-freq=0.05 --seed=$seed --restart-on-model -n 100"
echo "Seed: $seed"
echo "seed($seed).\n#begin_lua\nmath.randomseed($seed)\n#end_lua." > seed
echo "Grounding..."
time --format="%E, %K KB" clingo seed functions $sources -l > out/ground \
  || exit
echo "% vim: syn=gringo" >> out/ground
echo "  ...done."
echo "Solving..."
time --format="%E, %K KB"\
 clingo out/ground $opts |\
  sed "s/) /)\n/g" > out/s100
echo "% vim: syn=gringo" >> out/s100
echo "  ...done."
